### PR TITLE
Fix for #89, overdub with invoke and optional arguments

### LINKED ISSUE #89: Overdub hates `reverse`...
Of course it isn't literally `reverse`, but that is the only function I've found so far that does this.

### MWE (as minimal as I've managed to get so far)
```
using Cassette
Cassette.@context CTX31

foobuzz(args...) = -1
function binger()
    reverse(foobuzz())
end

function Cassette.execute(ctx::CTX31, ::typeof(foobuzz))
    [1,2,3]
end

Cassette.@overdub(CTX31(), binger())
```

### Error is
```
ERROR: MethodError: no method matching Tuple{AbstractArray{T,1} where T}(::Array{Int64,1}, ::Int64, ::Int64)
Closest candidates are:
  Tuple{AbstractArray{T,1} where T}(::Any) where T<:Tuple at tuple.jl:243
Stacktrace:
 [1] call at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/context.jl:441 [inlined]
 [2] fallback at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/context.jl:439 [inlined]
 [3] macro expansion at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/overdub.jl:403 [inlined]
 [4] overdub at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/overdub.jl:437 [inlined]
 [5] reverse at ./array.jl:1453 [inlined]
 [6] overdub(::Cassette.Context{nametype(CTX31),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(invoke), ::typeof(reverse), ::Type{Tuple{AbstractArray{T,1} where T}}, ::Array{Int64,1}) at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/overdub.jl:0
 [7] reverse at ./array.jl:1467 [inlined]
 [8] overdub(::Cassette.Context{nametype(CTX31),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(reverse), ::Array{Int64,1}) at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/overdub.jl:0
 [9] binger at ./REPL[4]:2 [inlined]
 [10] overdub(::Cassette.Context{nametype(CTX31),Nothing,Cassette.NoPass,Nothing,Nothing}, ::typeof(binger)) at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/overdub.jl:0
 [11] overdub(::Cassette.Context{nametype(CTX31),Nothing,Cassette.NoPass,Nothing,Nothing}, ::getfield(Main, Symbol("##8#9"))) at /Users/oxinabox/.julia/packages/Cassette/ZJvy1/src/overdub.jl:490
 [12] top-level scope at none:0
```

Swapping out the  `reverse(foobuz())` for `identity(foobuz())`, or `collect(foobuz())` or `foobuzz()[2]` works without issue.

### PR DESCRIPTION
**Pull request by tkoolen**
I'm still trying to wrap my head around the package internals, but this seems to fix #89 and I think this kind of makes sense. The old behavior of adding a constant `invoke_offset` of 2 to all argument slots seemed kind of weird to me, since `untagged_args` in `__overdub_generator__` ends up looking like `(typeof(invoke), typeof(f), Type{Tuple{Int64}}, Int64)`, i.e. the first and third arguments should be skipped, rather than the first two.

### CODE REVIEW

File: src/overdub.jl [hunk 1]
```diff
@@ -180,6 +180,9 @@ function overdub_pass!(reflection::Reflection,
     for i in 1:n_method_args
         slot = i + n_prepended_slots
         offset = i + invoke_offset
+        if is_invoke && i == 1
+            invoke_offset += 1
+        end
         if is_invoke && is_calloverload && i == 1
             offset = 2 # 1 is invoke, 2 is f, 3 is Tuple{}, 4... is args
```
Comment (tkoolen) [inline src/overdub.jl]: I don't understand this part of the code, so please check carefully.

**Comment by tkoolen** [comment]
I suppose the vararg branch should be fixed as well, right?

https://github.com/jrevels/Cassette.jl/blob/427dabc4cb5da00b1c84a2dcdcb9640e0f05e307/src/overdub.jl#L206

File: src/overdub.jl (hunk 1 above)
Comment (vchuravy) [reply src/overdub.jl]: This does make sense to me. I am not sure about it either.

@jrevels any recollection why it was the way it is?

Comment (tkoolen) [reply src/overdub.jl]: FYI, with this comment I was referring specifically to lines 186-187; I didn't understand why `is_calloverload` is treated separately.

Comment (vchuravy) [reply src/overdub.jl]: Ah that makes sense. I am to blame for that code (https://github.com/jrevels/Cassette.jl/pull/128) 

`is_calloverload` was trying to fix a very similar issue, where when you do call overloading you end up with code that looks similar to what you seem to run into.

**Comment by tkoolen** [comment]
I've cleaned up the offset calculation code a little (removed the `is_calloverload` special case). I believe the vararg handling is (and was) right as well.

**Comment by tkoolen** [comment]
I verified that the example from https://github.com/jrevels/Cassette.jl/issues/127#issue-451158553 still works with this change.

**Comment by tkoolen** [comment]
Do you need anything else from me?

**Comment by vchuravy** [comment]
Thanks!
